"""empty message

Revision ID: 179675505660
Revises: None
Create Date: 2016-12-08 10:53:59.420489

"""

# revision identifiers, used by Alembic.
revision = '179675505660'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('finished_role_selection', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'finished_role_selection')
    ### end Alembic commands ###
