"""empty message

Revision ID: 3b069965e8ca
Revises: 4e2406e3395c
Create Date: 2016-11-07 15:04:03.245766

"""

# revision identifiers, used by Alembic.
revision = '3b069965e8ca'
down_revision = '4e2406e3395c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('episodeName', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'episodes', ['episodeName'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'episodes', type_='unique')
    op.drop_column('episodes', 'episodeName')
    ### end Alembic commands ###
