"""empty message

Revision ID: 4e2406e3395c
Revises: 89ef9e4ff078
Create Date: 2016-11-07 14:40:48.413753

"""

# revision identifiers, used by Alembic.
revision = '4e2406e3395c'
down_revision = '89ef9e4ff078'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episodeJSON', sa.String(length=30000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episodeJSON')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=False),
    sa.Column('lastName', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('episodes')
    ### end Alembic commands ###
