"""empty message

Revision ID: 7de0f6445c08
Revises: 38a225ff6a1d
Create Date: 2016-11-11 15:59:01.386122

"""

# revision identifiers, used by Alembic.
revision = '7de0f6445c08'
down_revision = '38a225ff6a1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    ### end Alembic commands ###
