"""empty message

Revision ID: 7f8167444d20
Revises: None
Create Date: 2016-08-13 16:18:14.217501

"""

# revision identifiers, used by Alembic.
revision = '7f8167444d20'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    ### end Alembic commands ###
