"""empty message

Revision ID: 8d069a1d8e0b
Revises: 4b80f1cd230a
Create Date: 2016-12-07 08:24:57.994425

"""

# revision identifiers, used by Alembic.
revision = '8d069a1d8e0b'
down_revision = '4b80f1cd230a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    ### end Alembic commands ###
