"""empty message

Revision ID: 9a32178ce187
Revises: cc9ea85b68bb
Create Date: 2016-11-17 17:52:23.709596

"""

# revision identifiers, used by Alembic.
revision = '9a32178ce187'
down_revision = 'cc9ea85b68bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'episode', ['episodeJSONFileName'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'episode', type_='unique')
    ### end Alembic commands ###
