"""empty message

Revision ID: b04dcae9e3a1
Revises: c97b268d3a63
Create Date: 2016-09-14 12:49:10.704429

"""

# revision identifiers, used by Alembic.
revision = 'b04dcae9e3a1'
down_revision = 'c97b268d3a63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_user')
    op.drop_table('teachers')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'teachers_pkey')
    )
    op.create_table('teacher_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.Column('reset_password_token', sa.VARCHAR(length=100), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'teacher_user_pkey'),
    sa.UniqueConstraint('email', name=u'teacher_user_email_key'),
    sa.UniqueConstraint('username', name=u'teacher_user_username_key')
    )
    ### end Alembic commands ###
