"""empty message

Revision ID: cc9ea85b68bb
Revises: 7de0f6445c08
Create Date: 2016-11-17 12:46:04.357358

"""

# revision identifiers, used by Alembic.
revision = 'cc9ea85b68bb'
down_revision = '7de0f6445c08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'episode_episodeJSONFileName_key', 'episode', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'episode_episodeJSONFileName_key', 'episode', ['episodeJSONFileName'])
    ### end Alembic commands ###
