"""empty message

Revision ID: d305b2dcdc31
Revises: 3b069965e8ca
Create Date: 2016-11-07 15:20:02.279745

"""

# revision identifiers, used by Alembic.
revision = 'd305b2dcdc31'
down_revision = '3b069965e8ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('episodeAssigned', sa.Boolean(), nullable=False))
    op.add_column('episodes', sa.Column('episodeJSONFileName', sa.String(length=30), nullable=False))
    op.drop_constraint(u'episodes_episodeJSON_key', 'episodes', type_='unique')
    op.drop_constraint(u'episodes_episodeName_key', 'episodes', type_='unique')
    op.create_unique_constraint(None, 'episodes', ['episodeJSONFileName'])
    op.drop_column('episodes', 'episodeName')
    op.drop_column('episodes', 'episodeJSON')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('episodeJSON', sa.VARCHAR(length=30000), autoincrement=False, nullable=False))
    op.add_column('episodes', sa.Column('episodeName', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'episodes', type_='unique')
    op.create_unique_constraint(u'episodes_episodeName_key', 'episodes', ['episodeName'])
    op.create_unique_constraint(u'episodes_episodeJSON_key', 'episodes', ['episodeJSON'])
    op.drop_column('episodes', 'episodeJSONFileName')
    op.drop_column('episodes', 'episodeAssigned')
    ### end Alembic commands ###
