"""empty message

Revision ID: d5bff4759c27
Revises: 7f8167444d20
Create Date: 2016-08-13 17:03:54.959863

"""

# revision identifiers, used by Alembic.
revision = 'd5bff4759c27'
down_revision = '7f8167444d20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('firstName', sa.String(length=30), nullable=False))
    op.add_column('teachers', sa.Column('lastName', sa.String(length=30), nullable=False))
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('teachers', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('teachers', 'lastName')
    op.drop_column('teachers', 'firstName')
    ### end Alembic commands ###
