"""empty message

Revision ID: e997b1c0990c
Revises: fd433caaa3bc
Create Date: 2016-11-17 22:59:54.005519

"""

# revision identifiers, used by Alembic.
revision = 'e997b1c0990c'
down_revision = 'fd433caaa3bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('episode_teacher_id', 'episodes', ['episode_id', 'teacher_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('episode_teacher_id', 'episodes', type_='unique')
    ### end Alembic commands ###
